### ISSUE TITLE
Visualizer doesn't work with volume or shape.

### ISSUE THREAD

**Issue by mwillsey** [uwmisl/puddle#20]
Right now (as of d74a3ca6f500308fb34438ce16546c8fe0533966), the visualizer doesn't work at all. It should:
- be fixed to at least show something
- support volume
- have rudimentary support for shape

We can mostly ignore shape in the visualizer because large droplets never get made, but the support should be there.

**Comment by chrstnb** [comment]
One issue: 
![rounded-rect](https://user-images.githubusercontent.com/22881644/37173828-8f7b1fc8-22c9-11e8-8a05-9a877c45c2fe.png) 

Rounded rectangle is likely not our best option. Using [ellipse](https://photonstorm.github.io/phaser-ce/Phaser.Graphics.html#drawEllipse) instead.

**Comment by mwillsey** [comment]
I would say to stick with rounded rect but maybe increase the radius. With
ellipse you might find it hard to cover all of the cells in the rectangle
when it's large.

**Comment by mwillsey** [comment]
> I tried the whole range of radius options

What do you mean here? I think it's more important to accurately cover all of the cells that the droplet covers.

**Comment by chrstnb** [comment]
I mean attempting to get it to resemble a circle/ellipse. There's not the best documentation in terms of the relationship between the radius and the dimensions of the object; I think what I have now is close. Was mostly concerned about the note in the docs "[In WebGL this must be a value between 0 and 9](https://photonstorm.github.io/phaser-ce/Phaser.Graphics.html)", but it appears it's not really an issue anymore per [this discussion](https://github.com/photonstorm/phaser/issues/1822)?
