### ISSUE TITLE
Use canvas for visualizations

### ISSUE THREAD

**Issue by chrstnb** [uwmisl/puddle#6]

**Comment by mwillsey** [comment]
This is pretty much necessary if we want to actually test the computer vision system.

**Comment by chrstnb** [comment]
Hoping I did the workflow correctly; not sure if there's a way to associate a branch with an issue, but [here's the branch](https://github.com/mwillsey/puddle/tree/canvas-viz)

It still needs a bit of work but I wanted feedback before I proceeded with some other features/expansions. 

One thing I'm wondering is whether it's better to try to replicate the object-oriented DOM approach with the droplets; as it is now there are new droplets being created at every frame and they're indexed by ID, which will make the 'time machine' concept a bit smoother, however it might be more efficient/cleaner to store the locations over time within each droplet object, in which case it might make sense to pull some of the comparison/animation behavior into it as well.
